### ISSUE TITLE
[BUG] Compilation error with MATX_ENABLE_CUTLASS in transforms/matmul.h

### ISSUE THREAD

**Issue by bk8190** [NVIDIA/MatX#605]
**Describe the Bug**
Compilation error in MatX/include/matx/transforms/matmul.h when building with MATX_EN_CUTLASS=on

Regression seems to have be introduced by https://github.com/NVIDIA/MatX/commit/d75d7025d7ed604de3529382691fb7ad4bfdfb2a
The commit replaces "idx" with "a_idx" "b_idx" and "c_idx".  The variable "idx" likely needs to be updated in the #if MATX_ENABLE_CUTLASS block starting on line 948

**Comment by cliffburdick** [comment]
Hi @bk8190 , we were not aware of anyone using the cutlass interface since it's untested. We will take a look and make sure it compiles. Can I ask why you're using this over the default cublas interface?

**Comment by bk8190** [comment]
Hi @cliffburdick - I am experimenting with the library and saw the option in the main CMakeLists.txt so I figured I would give it a try, but if it's untested I will stay clear

**Comment by cliffburdick** [comment]
@bk8190 it was working several months back, but because of the compile times it was taking far too long to test. We had to put it on hold in favor of cuBLAS because of the compile times. CUTLASS does have a few more capabilities that cuBLAS did not have at the time, like non-affine indexing, but the compile times were ultimately not something we could deal with for now. If you have a reason to use it over cuBLAS please let us know.
